{{- if .Values.certificate }}
{{- if .Values.certificate.enabled }}
{{- $c := .Values.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
{{ include "application.labels.metadata" . | indent 4 }}
{{- if $c.additionalLabels }}
{{ toYaml $c.additionalLabels | indent 4 }}
{{- end }}
{{- if $c.annotations }}
  annotations:
{{ toYaml $c.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}-certificate
  namespace: {{ template "application.namespace" . }}
spec:
  secretName: {{ include "application.tplvalues.render" ( dict "value" $c.secretName "context" $ ) }}
  duration: {{ $c.duration }}
  renewBefore: {{ $c.renewBefore }}
  {{- with $c.subject }}
  subject:
{{ include "application.tplvalues.render" ( dict "value" . "context" $ ) | indent 4 }}
  {{- end }}
  commonName: {{ include "application.tplvalues.render" ( dict "value" $c.commonName "context" $ )  }}
  {{- if $c.isCA }}
  isCA: {{ $c.isCA }}
  {{- end }}
  {{- with $c.usages }}
  usages:
{{ toYaml . | indent 4 }}
  {{- end }}
  # At least one of a DNS Name, URI, or IP address is required.
  {{- with $c.dnsNames }}
  dnsNames:
{{ include "application.tplvalues.render" ( dict "value" . "context" $ ) | indent 4 }}
  {{- end }}
  {{- with $c.ipAddresses }}
  ipAddresses:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with $c.uriSANs }}
  uris:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with $c.emailSANs }}
  emailAddresses:
{{ toYaml . | indent 4 }}
  {{- end }}
  privateKey:
    algorithm: {{ $c.keyAlgorithm | upper }}
    encoding: {{ $c.keyEncoding | upper }}
    size: {{ $c.keySize }}
    {{- if and $c.privateKey $c.privateKey.enabled }}
    rotationPolicy: {{ $c.privateKey.rotationPolicy }}
    {{- end }}
  issuerRef:
    name: {{ $c.issuerRef.name }}
    kind: {{ $c.issuerRef.kind }}
    {{- with $c.issuerRef.group }}
    group: {{ . }}
    {{- end }}
  {{- with $c.keystores }}
  keystores:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
