{{- if .Values.deployment }}
{{- if .Values.deployment.enabled }}
{{- $d := .Values.deployment }}
{{- $name := include "application.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "application.labels.metadata" . | indent 4 }}
{{- if $d.additionalLabels }}
{{ toYaml $d.additionalLabels | indent 4 }}
{{- end }}
{{- if or $d.annotations .Values.commonAnnotations }}
  annotations:
{{ toYaml (merge (dict) (default (dict) $d.annotations) (default (dict) .Values.commonAnnotations)) | indent 4 }}
{{- end }}
  name: {{ $name }}
  namespace: {{ template "application.namespace" . }}
spec:
{{- if not (kindIs "invalid" $d.replicas) }}
  replicas: {{ $d.replicas }}
{{- end }}
{{- if not (kindIs "invalid" $d.revisionHistoryLimit) }}
  revisionHistoryLimit: {{ $d.revisionHistoryLimit }}
{{- end }}
{{- with $d.minReadySeconds }}
  minReadySeconds: {{ . }}
{{- end }}
{{- with $d.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
{{- end }}
  selector:
    matchLabels:
{{ include "application.labels.selector" . | indent 6 }}
  {{- if $d.strategy }}
  strategy:
{{ toYaml $d.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
{{ include "application.labels.pod" (dict "root" $ "podLabels" $d.podLabels) | indent 8 }}
{{- if or $d.additionalPodAnnotations $d.fluentdConfigAnnotations .Values.commonAnnotations }}
      annotations:
{{- end }}
{{- with (merge (dict) (default (dict) $d.additionalPodAnnotations) (default (dict) .Values.commonAnnotations)) }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- if $d.fluentdConfigAnnotations }}
        fluentdConfiguration: >
          [
            {
              "containers":
              [
                {
                  "expressionFirstLine": "{{ $d.fluentdConfigAnnotations.regexFirstLine }}",
                  "expression": "{{ $d.fluentdConfigAnnotations.regex }}",
                  "timeFormat": "{{ $d.fluentdConfigAnnotations.timeFormat }}",
                  "containerName": "{{ $d.containerName | default $name }}"
                }
              ]{{- with $d.fluentdConfigAnnotations.notifications }},
              "notifications": {
                {{- with .slack }}
                "slack": {
                  "webhookURL": "{{ .webhookURL }}",
                  "channelName": "{{ .channelName }}"
                },
                {{- end }}
                "key": "{{ .key }}",
                "pattern": "{{ .pattern }}"
              }
              {{- end }}
            }
          ]
{{- end }}
    spec:
      {{- if $d.hostAliases }}
      hostAliases:
{{ toYaml $d.hostAliases | indent 6 }}
      {{- end }}
      {{- if $d.initContainers }}
      initContainers:
  {{- range $key, $value := $d.initContainers  }}
      - name: {{ $key }}
{{ include "application.tplvalues.render" ( dict "value" $value "context" $ ) | indent 8 }}
      {{- end }}
      {{- end }}
{{ include "application.podSpecCommon" (dict "root" $ "workload" $d) | indent 6 }}
      {{- if $d.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ $d.imagePullSecrets }}
      {{- end }}
      containers:
      - name: {{ $d.containerName | default $name }}
        image: {{ include "application.image" $d.image | quote }}
        {{- with $d.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        {{- if $d.command }}
        command: {{- include "application.tplvalues.render" (dict "value" $d.command "context" $) | nindent 12 }}
        {{- end }}
        {{- if $d.args }}
        args: {{- include "application.tplvalues.render" (dict "value" $d.args "context" $) | nindent 12 }}
        {{- end }}
        {{- if $d.ports }}
        ports:
{{ toYaml $d.ports | indent 10 }}
        {{- end }}
        {{- with $d.lifecycle }}
        lifecycle:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- if $d.envFrom }}
        envFrom:
        {{- range $value := $d.envFrom }}
        {{- if (eq .type "configmap") }}
        - configMapRef:
            {{- if .name }}
            name: {{ include "application.tplvalues.render" ( dict "value" $value.name "context" $ ) }}
            {{- else if .nameSuffix }}
            name: {{ $name }}-{{ include "application.tplvalues.render" ( dict "value" $value.nameSuffix "context" $ ) }}
            {{- else }}
            name: {{ $name }}
            {{- end }}
        {{- end }}
        {{- if (eq .type "secret") }}
        - secretRef:
            {{- if .name }}
            name: {{ include "application.tplvalues.render" ( dict "value" $value.name "context" $ ) }}
            {{- else if .nameSuffix }}
            name: {{ $name }}-{{ include "application.tplvalues.render" ( dict "value" $value.nameSuffix "context" $ ) }}
            {{- else }}
            name: {{ $name }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- $env := include "application.env" (dict "root" $ "workload" $d "name" $name) }}
        {{- if $env }}
        env:
{{ $env | indent 8 }}
        {{- end }}
        {{- if and $d.startupProbe $d.startupProbe.enabled }}
        startupProbe:
{{ include "application.probe" (dict "probe" $d.startupProbe "context" $) | indent 10 }}
        {{- end }}
        {{- if and $d.livenessProbe $d.livenessProbe.enabled }}
        livenessProbe:
{{ include "application.probe" (dict "probe" $d.livenessProbe "context" $) | indent 10 }}
        {{- end }}
        {{- if and $d.readinessProbe $d.readinessProbe.enabled }}
        readinessProbe:
{{ include "application.probe" (dict "probe" $d.readinessProbe "context" $) | indent 10 }}
        {{- end }}
      {{- if or ($d.volumeMounts) (and (eq .Values.persistence.enabled true) (eq .Values.persistence.mountPVC true) )}}
        volumeMounts:
        {{- if (eq .Values.persistence.mountPVC true) }}
        - mountPath: {{ .Values.persistence.mountPath }}
          name: {{ $name }}-data
        {{- end }}
        {{- if $d.volumeMounts }}
        {{- range $key, $value := $d.volumeMounts }}
        - name: {{ $key }}
{{  include "application.tplvalues.render" ( dict "value" $value "context" $ ) | indent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
        {{- with $d.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with $d.containerSecurityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- if $d.additionalContainers }}
{{ toYaml $d.additionalContainers | indent 6 }}
        {{- end }}
      {{- if or $d.volumes (and (eq .Values.persistence.enabled true) (eq .Values.persistence.mountPVC true)) }}
      volumes:
        {{- if and (eq .Values.persistence.enabled true) (eq .Values.persistence.mountPVC true) }}
      - name: {{ $name }}-data
        persistentVolumeClaim:
          claimName: {{ $name }}-data
        {{- end }}
        {{- range $key, $value := $d.volumes  }}
      - name: {{ $key  }}
{{ include "application.tplvalues.render" ( dict "value" $value "context" $ ) | indent 8 }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
{{- end }}
{{- end }}
