{{- if .Values.pdb.enabled }}
{{- if or .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
{{ include "application.labels.metadata" . | indent 4 }}
{{- if .Values.pdb.additionalLabels }}
{{ toYaml .Values.pdb.additionalLabels | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
{{ include "application.labels.selector" . | indent 6 }}
{{- end }}
{{- end }}
