{{- if and .Values.rbac.enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "application.labels.metadata" $ | indent 4 }}
{{- if $.Values.rbac.additionalLabels }}
{{ toYaml $.Values.rbac.additionalLabels | indent 4 }}
{{- end }}
{{- if .roleLabels }}
{{ toYaml .roleLabels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
  name: {{ .roleName | default (printf "%s-role-%s" (include "application.name" $) .name) }}
  namespace: {{ template "application.namespace" $ }}
rules:
{{ toYaml .rules | indent 2 }}
{{- end }}
{{- end }}
