{{- if .Values.serviceMonitor }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
{{ include "application.labels.serviceMonitor" . | indent 4 }}
{{- if .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}-svc-monitor
  namespace: {{ template "application.namespace" . }}
spec:
  selector:
    matchLabels:
{{ include "application.labels.selector" . | indent 6 }}
  namespaceSelector:
    matchNames:
    - {{ template "application.namespace" . }}
  endpoints:
{{ toYaml .Values.serviceMonitor.endpoints | indent 4 }}
{{- end }}
{{- end }}
