name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

  workflow_dispatch:
env:
  CHART_NAME: "application"
  CHART_PATH: "charts/application"
jobs:
  build:
    runs-on: ubuntu-latest 
    name: Build
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}
    - name: Setup Ephemeral Kubernetes Testing Cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"    
    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_PATH}
    # Dry run to ensure that manifests are generated successfully 
    - name: Dry Run Chart
      run: |
        helm install ${CHART_NAME} ${CHART_PATH} -f ${CHART_PATH}/values.yaml -n helm-chart-pipeline-test --dry-run --debug
    # package
    - name: Helm Package
      run: |
        helm package ${CHART_PATH}
    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Validation Successful'
        allow-repeats: false
    - name: Notify Failure
      if: failure()
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: false
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SRE_TEAM_SLACK_WEBHOOK }}
  
