name: Push
concurrency: 
 group: push_on_main
 cancel-in-progress: false
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'      
env:
  CHART_NAME: "application"
jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    # Generate tag for chart without "v" prefix
    - name: Generate Tag
      id: generate_tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        DRY_RUN: true
    # Update chart tag to the latest semver tag
    - name: Update Chart Version
      env:
        VERSION: ${{ steps.generate_tag.outputs.new_tag }}
      run: |
        make bump-chart
    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_NAME}
    # Dry run to ensure that manifests are generated successfully 
    - name: Dry Run Chart
      run: |
        helm install ${CHART_NAME} ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml -n helm-chart-pipeline-test --dry-run --debug
    # Publish helm chart
    - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@master
      with:
        branch: main
        repository: apps-helm-charts
        target_dir: docs
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: .
        charts_url: https://jupiterone.github.io/apps-helm-charts
        owner: JupiterOne
        linting: off 
        commit_username: jupiterone-helm-chart-bot
        commit_email: sre@jupiterone.io
    # Commit back changes
    - name: Commit files
      run: |
        git config --local user.email "sre@jupiterone.io"
        git config --local user.name "jupiterone-helm-chart-bot"
        git status 
        git add application/Chart.yaml
        git commit -m "[skip-ci] Update artifacts" 
    # Push Chart.yaml with Updated Version
    - name: Push changes
      shell: bash {0}
      run: |
        git config --local user.email "sre@jupiterone.io"
        git config --local user.name "jupiterone-helm-chart-bot"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push origin
        if [ $? -eq 0 ]; then
            echo OK Pushed Succesfully.
        else
          for i in 1 2 3
          do
            echo "Trying Push Again Attempt:" $i
            git pull --rebase --strategy-option theirs
            if [ $? -eq 0 ]; then
                echo OK Pulled
            else
                continue
            fi
            git push origin
            if [ $? -eq 0 ]; then
                echo OK Pushed
                break
            else
                if [ $i -eq 3 ];then
                 echo "Fail: Couldnt Push to Remote"
                 exit 1
                fi
                continue
            fi
          done
        fi
  
    - name: Push Latest Tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Clean up KUBECONFIG
      if: always() 
      run: |
         rm $KUBECONFIG
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SRE_TEAM_SLACK_WEBHOOK }}
