name: Push
concurrency: 
 group: push_on_main
 cancel-in-progress: false
on:
  push:
    branches:
      - main    
env:
  CHART_NAME: "application"
  CHART_PATH: "charts/application"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "! contains(github.event.commits.$${github.event.size - 1}}.message, '[skip-ci]')"    

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Setup Ephemeral Kubernetes Testing Cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"    
    # Generate tag for chart without "v" prefix
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: Display GitVersion outputs
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
    # Update chart tag to the latest semver tag
    - name: Update Chart Version
      env:
        VERSION: ${{ steps.gitversion.outputs.semVer }}
      run: |
        make bump-chart
    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_PATH}
    # Dry run to ensure that manifests are generated successfully 
    - name: Dry Run Chart
      run: |
        helm install ${CHART_NAME} ${CHART_PATH} -f ${CHART_PATH}/values.yaml -n test --dry-run --debug
    # Publish helm chart
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Commit files
      run: |
        git config --local user.email "sre@jupiterone.com"
        git config --local user.name "jupiterone-helm-chart-bot"
        git status 
        git add ${CHART_PATH}/Chart.yaml
        git commit -m "[skip-ci] Updated application helm chart version to: ${{ steps.gitversion.outputs.semVer }}"     
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SRE_TEAM_SLACK_WEBHOOK }}
